apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/deep75-users-noreply-github-com/fcdemo3:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/deep75-users-noreply-github-com/fcdemo3:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: fcdemo3
        chartPath: charts/fcdemo3
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/deep75-users-noreply-github-com/fcdemo3"
          image.tag: "{{.DIGEST_HEX}}"
